export const typeColors = {
   normal: "#D0D0D0",
   fire: "#F7786b",
   water: "#58ABF6",
   electric: "#FFCE4B",
   grass: "#2CDAB1",
   ice: "#8ED2F9",
   fighting: "#FF922E",
   poison: "#6D31D0",
   ground: "#E2BF65",
   flying: "#CBCBF2",
   psychic: "#FF66B2",
   bug: "#08A47F",
   rock: "#A38C21",
   ghost: "#705693",
   dragon: "#8A76FF",
   dark: "#6E6E6E",
   steel: "#B8B8D0",
   fairy: "#F0B6BC",
   animal: "#9f0400",
   sand: "#f0ff05",
   sound: "#ef00e7",
   speedy: "#c3c7cc",
   unknown: "#000000",
};

export enum PokemonTypeEnum {
   normal = "normal",
   fire = "fire", 
   water = "water",
   electric = "electric",
   grass = "grass",
   ice = "ice",   
   fighting = "fighting",
   poison = "poison",
   ground = "ground",
   flying = "flying",   
   psychic = "psychic",
   bug = "bug",
   rock = "rock",
   ghost = "ghost",
   dragon = "dragon",
   dark = "dark",
   steel = "steel",
   fairy = "fairy",
   animal = "animal",
   sand = "sand",
   sound = "sound",
   speedy = "speedy",
   unknown = "unknown",
}
